### ISSUE TITLE
Hides 'All Users'

### ISSUE THREAD

**Issue by wihodges** [jalendport/craft-hideadmin#11]
Is there a way for it to not hide the 'All Users' group in the sidebar.  Issue is that when a non admin user creates a new users and forgets to add permission group to the new user, the user is then invisible to non-admins. 

Very useful plugin, thank you.

**Comment by wihodges** [comment]
Is there a fix for this or is this just how the plugin is expected to work. I can't seem to figure out any work around. Like would be nice if Craft would add new user by default to a specified group.

**Comment by jalendport** [comment]
Sorry for the long delay on this - not sure if you're still using this plugin, but there is a fix for this now in version [1.2.0](https://github.com/jalendport/craft-hideadmin/releases/tag/1.2.0)
